### ISSUE TITLE
Only works on Windows

### ISSUE THREAD

**Issue by RealDekkia** [wladi0097/Kerberos-Chat#1]
node-sspi only works on Windows-OSes
>NodeSSPI to Node.js is what mod-auth-sspi to Apache HTTPD. In a nutshell NodeSSPI authenticates incoming HTTP(S) requests through native Windows SSPI, hence NodeSSPI runs on Windows only.

https://www.npmjs.com/package/node-sspi

**Comment by wladi0097** [comment]
This project was made for a windows only enviroment, I'm sorry
